### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "adminadmin",
    "password": "admin"
}

### find User By id
GET http://localhost:3000/auth/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJ1c2VybmFtZSI6ImFkbWludXNlcjEiLCJyb2xlIjoiQURNSU4iLCJpc19hY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjItMDUtMTNUMTQ6MDQ6MTYuNzE4WiIsInVwZGF0ZWRBdCI6IjIwMjItMDUtMTNUMTQ6MDQ6MTYuNzE4WiJ9LCJpYXQiOjE2NTI0NTA2NjUsImV4cCI6MTY1MjQ1NDI2NX0.Vz0ZHjjV5Jyxwq1cA3nIp0oDCQlMEBBAF7ebzWTQfiA


### find all users
GET http://localhost:3000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJ1c2VybmFtZSI6ImFkbWludXNlcjEiLCJyb2xlIjoiQURNSU4iLCJpc19hY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjItMDUtMTNUMTQ6MDQ6MTYuNzE4WiIsInVwZGF0ZWRBdCI6IjIwMjItMDUtMTNUMTQ6MDQ6MTYuNzE4WiJ9LCJpYXQiOjE2NTMyMTczMjgsImV4cCI6MTY1MzIyMDkyOH0.OTZuzRSOgzg-u1DLfz2aBIg70k7jIYWJw3TKBl4XZ34

### Create Employee
POST http://localhost:3000/auth/register/employee
Content-Type: application/json

{
    "name": "Employee2",
    "familyMember": ["bot1", "bot2"],
    "contact": {
        "phone": "0132222359",
        "email": "employee2@gmial.com"
    },
    "dob": "2000-12-12",
    "gender": "MALE",
    "address": "Saturn",
    "positionId": 9,
    "subDivisonId": 17
}

### Block Employee By id
PATCH http://localhost:3000/auth/user/block/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiYWRtaW51c2VyMSIsImlzX2FjdGl2ZSI6dHJ1ZX0sImlhdCI6MTY1MzIyMDY0MywiZXhwIjoxNjUzMjI0MjQzfQ.yd51xpKaPVVRvEo9Jq-loE9WiTXl_cJEAPYzNPQJx4c