### Create Invoice
POST http://localhost:3000/invoice
Content-Type: application/json

{
    "supplierId": 1,
    "purchaseDate": "2022-05-31T09:38:09.228Z",
    "employeeId": 41,
    "paymentStatus": "Unpaid",
    "details": "details",
    "purchaseItems": [
        {
            "productId": 15,
            "stockQty": 5,
            "rate": 34,
            "quantity": 34,
            "total": "$1,156.00"
        }
    ]
}

{
    "supplierId": 1,
    "purchaseDate": "2022-05-31T09:54:59.587Z",
    "employeeId": 0,
    "paymentStatus": "Unpaid",
    "details": "details",
    "purchaseItems": [
        {
            "productId": 15,
            "stockQty": 5,
            "rate": 34,
            "quantity": 34,
            "total": "$1,156.00"
        },
        {
            "productId": 12,
            "stockQty": "",
            "rate": 3,
            "quantity": 33,
            "total": "$99.00"
        }
    ]
}

### Update Invoice
PATCH http://localhost:3000/invoice/181
Content-Type: application/json

{
    "purchaseDate": "2022-12-12",
    "supplierId": 2,
    "employeeId": 1,
    "paymentStatus": "Paid",
    "createPurchaseItemDto": [
        {
            "productId": 7,
            "rate": 100,
            "quantity": 10
        },
        {
            "productId": 5,
            "rate": 100,
            "quantity": 10
        }
    ]
}


### Find Invoice By id
GET http://localhost:3000/invoice/36


### Find All Invoices
GET http://localhost:3000/invoice