### Update Employee
PATCH http://localhost:3000/employee/update/4
Content-Type: application/json

{
    "name": "admin",
    "familyMember": ["Xiaoting", "Mike", "Small John"],
    "contact": {
        "phone": "0900000000",
        "email": "admin@gmial.com"
    },
    "dob": "2000-12-12",
    "gender": "MALE",
    "positionId": 9,
    "subDivisonid": 11,
    "role": "ADMIN"
}

### Get employee by id
GET http://localhost:3000/employee/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWludXNlciIsInJvbGUiOiJBRE1JTiIsImlzX2FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMi0wNS0xM1QwOTo0MTozNC44MjNaIiwidXBkYXRlZEF0IjoiMjAyMi0wNS0xM1QwOTo0MTozNC44MjNaIn0sImlhdCI6MTY1MjQ0OTMxNywiZXhwIjoxNjUyNDUyOTE3fQ.uVgzTOIaOTRcZLdP_9kE2KcYgU8UvEJ1Gvh1wNAprNA


### Get All employees
GET http://localhost:3000/employee


### Upload Image (Test with postman)
POST http://localhost:3000/employee/upload-image/3


### find Employee's ImageName
GET http://localhost:3000/employee/image-name/3

### find Employee's Actual Image
GET http://localhost:3000/employee/actual-image/2